"use client";
import { useEffect, useState } from "react";
type Config = { configured: boolean; alias: string; provider: string; model: string; baseUrl: string; task: string; active: boolean; updatedAt: string | null; source: "database" | "environment" | "none" };
const empty: Config = { configured: false, alias: "Đánh giá hồ sơ ứng viên", provider: "Google Gemini", model: "gemini-3.6-flash", baseUrl: "https://generativelanguage.googleapis.com/v1beta", task: "Đánh giá hồ sơ ứng viên", active: true, updatedAt: null, source: "none" };
export default function AiConfigurationManager() {
 const [config,setConfig]=useState<Config>(empty),[open,setOpen]=useState(false),[apiKey,setApiKey]=useState(""),[alias,setAlias]=useState(empty.alias),[model,setModel]=useState(empty.model),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/gemini-key");const d=await r.json();if(!r.ok)throw new Error(d.error);setConfig(d);setAlias(d.alias);setModel(d.model)}catch(e){setMessage(e instanceof Error?e.message:"Không tải được cấu hình.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function request(method:string,body?:unknown){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/gemini-key",{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Thao tác thất bại.");setMessage(d.message||"Đã cập nhật cấu hình AI.");setOpen(false);setApiKey("");await load()}catch(e){setMessage(e instanceof Error?e.message:"Thao tác thất bại.")}finally{setBusy(false)}}
 function edit(){setAlias(config.alias);setModel(config.model);setApiKey("");setOpen(true)}
 return <div>
  <div className="mb-4 flex justify-end"><button className="btn-secondary" onClick={()=>{setApiKey("");setAlias(config.configured?config.alias:empty.alias);setModel(config.configured?config.model:empty.model);setOpen(true)}}>+ Thêm API Key</button></div>
  <div className="overflow-hidden rounded-[var(--radius-app)] border border-[var(--color-rule)] bg-[var(--color-paper)] shadow-sm">
  <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--color-rule)] px-5 py-4"><div><h2 className="font-bold">Danh sách API Key (AI)</h2><p className="mt-1 text-xs text-[var(--color-muted)]">Model đang kích hoạt sẽ được dùng trực tiếp khi đánh giá CV.</p></div></div>
  {message&&<div className="border-b border-[var(--color-rule)] bg-[var(--color-paper-2)] px-5 py-3 text-sm">{message}</div>}
  {loading?<p className="p-8 text-center text-sm text-[var(--color-muted)]">Đang tải...</p>:config.configured?<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[var(--color-paper-2)] text-xs uppercase text-[var(--color-muted)]"><tr><th className="px-5 py-3">Tên gợi nhớ</th><th className="px-5 py-3">Nhà cung cấp / Model</th><th className="px-5 py-3">Base URL</th><th className="px-5 py-3">Tác vụ được gán</th><th className="px-5 py-3">Kích hoạt</th><th className="px-5 py-3">Kết nối</th><th className="px-5 py-3">Thao tác</th></tr></thead><tbody><tr><td className="px-5 py-5 font-semibold">{config.alias}</td><td className="px-5 py-5"><div>{config.provider}</div><div className="text-xs text-[var(--color-muted)]">{config.model}</div></td><td className="max-w-[240px] break-all px-5 py-5 text-xs">{config.baseUrl}</td><td className="px-5 py-5"><span className="rounded bg-green-100 px-2 py-1 text-xs text-green-800">{config.task}</span></td><td className="px-5 py-5"><button aria-label="Bật hoặc tắt cấu hình" disabled={busy||config.source==='environment'} onClick={()=>request("PUT",{alias:config.alias,model:config.model,active:!config.active})} className={`relative h-6 w-11 rounded-full ${config.active?'bg-green-600':'bg-slate-300'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${config.active?'left-6':'left-1'}`}/></button></td><td className="px-5 py-5"><button className="btn-secondary px-3 py-2 text-xs" disabled={busy||!config.active} onClick={()=>request("POST")}>Kiểm tra</button></td><td className="px-5 py-5"><div className="flex gap-3"><button className="text-[var(--color-accent)]" onClick={edit}>Sửa</button><button className="text-red-600" disabled={busy||config.source==='environment'} onClick={()=>{if(confirm("Xóa cấu hình AI này?"))void request("DELETE")}}>Xóa</button></div></td></tr></tbody></table></div>:<div className="p-10 text-center"><p className="font-semibold">Chưa có cấu hình AI</p><p className="mt-2 text-sm text-[var(--color-muted)]">Thêm Gemini API key để bắt đầu đánh giá hồ sơ ứng viên.</p></div>}
  <div className="border-t border-[var(--color-rule)] px-5 py-3 text-xs text-[var(--color-muted)]">API key được mã hóa AES-256-GCM trước khi lưu. Hệ thống không gửi key về trình duyệt sau khi lưu.</div>
  {open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/55 p-4" onMouseDown={(e)=>{if(e.currentTarget===e.target)setOpen(false)}}><form onSubmit={(e)=>{e.preventDefault();void request("PUT",{alias,model,active:config.configured?config.active:true,...(apiKey?{apiKey}:{})})}} className="max-h-[calc(100vh-2rem)] w-full max-w-2xl overflow-y-auto rounded-[var(--radius-app)] bg-[var(--color-paper)] shadow-2xl"><div className="flex items-center justify-between border-b border-[var(--color-rule)] px-6 py-4"><h3 className="text-xl font-bold">{config.configured?'Sửa API Key':'Thêm API Key'}</h3><button type="button" onClick={()=>setOpen(false)} className="text-2xl text-[var(--color-muted)]">×</button></div><div className="grid gap-5 p-6 sm:grid-cols-2"><label className="text-sm font-semibold">Mã (code)<input className="input-field mt-2" value="recruitment-screening" readOnly/></label><label className="text-sm font-semibold">Tên gợi nhớ *<input className="input-field mt-2" value={alias} onChange={e=>setAlias(e.target.value)} required/></label><label className="text-sm font-semibold">Nhà cung cấp<input className="input-field mt-2" value="Google Gemini" readOnly/></label><label className="text-sm font-semibold">Model *<select className="input-field mt-2" value={model} onChange={e=>setModel(e.target.value)}><option value="gemini-3.6-flash">Gemini 3.6 Flash</option><option value="gemini-3.5-flash-lite">Gemini 3.5 Flash-Lite</option></select></label><label className="text-sm font-semibold sm:col-span-2">Base URL<input className="input-field mt-2" value={empty.baseUrl} readOnly/></label><label className="text-sm font-semibold sm:col-span-2">API Key {config.configured?'(để trống nếu không thay đổi)':'*'}<input type="password" autoComplete="off" className="input-field mt-2" value={apiKey} onChange={e=>setApiKey(e.target.value)} required={!config.configured} placeholder={config.configured?'••••••••••••':'Dán Gemini API key'}/><span className="mt-2 block text-xs font-normal text-[var(--color-muted)]">Key không được hiển thị lại sau khi lưu.</span></label><div className="sm:col-span-2"><p className="text-sm font-semibold">Gán cho chức năng AI</p><span className="mt-2 inline-block rounded-full border border-[var(--color-rule)] px-3 py-1 text-sm">Đánh giá hồ sơ ứng viên</span></div></div><div className="flex justify-end gap-3 border-t border-[var(--color-rule)] px-6 py-4"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Hủy</button><button className="btn-primary" disabled={busy}>{busy?'Đang lưu...':'Lưu API Key'}</button></div></form></div>}
  </div>
 </div>
}
