"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ROLE_LABELS, USER_ROLES, permissionsForRole, type UserRole } from "@/lib/permissions";
import type { AdminLocale } from "@/lib/admin-i18n";

type UserRow = { id: string; username: string; displayName: string | null; role: string; isActive: boolean; createdAt: string; updatedAt: string };

const labels = {
  vi: { add: "+ Thêm người dùng", create: "Tạo tài khoản mới", username: "Tên đăng nhập", display: "Họ tên / tên hiển thị", password: "Mật khẩu ban đầu", role: "Vai trò", creating: "Đang tạo...", createBtn: "Tạo tài khoản", cancel: "Hủy", user: "Người dùng", status: "Trạng thái", perms: "Quyền chính", actions: "Thao tác", active: "Đang hoạt động", disabled: "Đã khóa", you: "Bạn", reset: "Đặt lại MK", del: "Xóa", matrix: "Ma trận quyền mặc định", newPassword: "Nhập mật khẩu mới", deleteAsk: "Xóa tài khoản", createFail: "Không thể tạo người dùng.", updateFail: "Không thể cập nhật người dùng.", deleteFail: "Không thể xóa người dùng." },
  en: { add: "+ Add user", create: "Create new account", username: "Username", display: "Display name", password: "Initial password", role: "Role", creating: "Creating...", createBtn: "Create account", cancel: "Cancel", user: "User", status: "Status", perms: "Main permissions", actions: "Actions", active: "Active", disabled: "Disabled", you: "You", reset: "Reset password", del: "Delete", matrix: "Default permission matrix", newPassword: "Enter a new password", deleteAsk: "Delete account", createFail: "Could not create user.", updateFail: "Could not update user.", deleteFail: "Could not delete user." },
  "zh-TW": { add: "+ 新增使用者", create: "建立新帳號", username: "登入名稱", display: "顯示名稱", password: "初始密碼", role: "角色", creating: "建立中...", createBtn: "建立帳號", cancel: "取消", user: "使用者", status: "狀態", perms: "主要權限", actions: "操作", active: "啟用中", disabled: "已停用", you: "本人", reset: "重設密碼", del: "刪除", matrix: "預設權限矩陣", newPassword: "輸入新密碼", deleteAsk: "刪除帳號", createFail: "無法建立使用者。", updateFail: "無法更新使用者。", deleteFail: "無法刪除使用者。" },
} as const;

const permissionLabels: Record<AdminLocale, Record<string, string>> = {
  vi: { JOBS_MANAGE: "Quản lý tin tuyển dụng", APPLICATIONS_VIEW: "Xem hồ sơ", APPLICATIONS_MANAGE: "Xử lý hồ sơ", AI_EVALUATE: "Đánh giá AI", AI_CONFIGURE: "Cấu hình AI", EXPORT_RESULTS: "Xuất kết quả", USERS_MANAGE: "Quản lý người dùng" },
  en: { JOBS_MANAGE: "Manage jobs", APPLICATIONS_VIEW: "View applications", APPLICATIONS_MANAGE: "Manage applications", AI_EVALUATE: "AI evaluation", AI_CONFIGURE: "AI configuration", EXPORT_RESULTS: "Export results", USERS_MANAGE: "Manage users" },
  "zh-TW": { JOBS_MANAGE: "管理職缺", APPLICATIONS_VIEW: "查看履歷", APPLICATIONS_MANAGE: "處理履歷", AI_EVALUATE: "AI 評估", AI_CONFIGURE: "AI 設定", EXPORT_RESULTS: "匯出結果", USERS_MANAGE: "管理使用者" },
};

export default function UsersManager({ initialUsers, currentUserId, locale = "vi" }: { initialUsers: UserRow[]; currentUserId: string; locale?: AdminLocale }) {
  const router = useRouter(); const t = labels[locale];
  const [users, setUsers] = useState(initialUsers); const [showCreate, setShowCreate] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ username: "", displayName: "", password: "", role: "HR_USER" as UserRole });
  const roleSummary = useMemo(() => USER_ROLES.map((role) => ({ role, permissions: permissionsForRole(role) })), []);

  async function createUser() { setSaving(true); setError(""); const response = await fetch("/api/admin/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) return setError(data.error || t.createFail); setUsers((current) => [...current, data.user]); setForm({ username: "", displayName: "", password: "", role: "HR_USER" }); setShowCreate(false); router.refresh(); }
  async function patchUser(id: string, patch: Record<string, unknown>) { setError(""); const response = await fetch(`/api/admin/users/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); const data = await response.json().catch(() => ({})); if (!response.ok) return setError(data.error || t.updateFail); setUsers((current) => current.map((user) => (user.id === id ? data.user : user))); router.refresh(); }
  async function resetPassword(id: string, username: string) { const password = prompt(`${t.newPassword} ${username}:`); if (!password) return; await patchUser(id, { password }); }
  async function deleteUser(id: string, username: string) { if (!confirm(`${t.deleteAsk} "${username}"?`)) return; const response = await fetch(`/api/admin/users/${id}`, { method: "DELETE" }); const data = await response.json().catch(() => ({})); if (!response.ok) return setError(data.error || t.deleteFail); setUsers((current) => current.filter((user) => user.id !== id)); }

  return <div className="space-y-6"><div className="flex justify-end"><button type="button" className="btn-primary" onClick={() => setShowCreate((value) => !value)}>{t.add}</button></div>
    {showCreate && <div className="rounded-[var(--radius-app)] border border-[var(--color-rule)] bg-[var(--color-paper)] p-5 shadow-sm"><h2 className="text-lg font-bold">{t.create}</h2><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label className="block"><span className="mb-1 block text-sm font-semibold">{t.username}</span><input className="input-field" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /></label><label className="block"><span className="mb-1 block text-sm font-semibold">{t.display}</span><input className="input-field" value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} /></label><label className="block"><span className="mb-1 block text-sm font-semibold">{t.password}</span><input type="password" className="input-field" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><label className="block"><span className="mb-1 block text-sm font-semibold">{t.role}</span><select className="input-field" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as UserRole })}>{USER_ROLES.map((role) => <option key={role} value={role}>{ROLE_LABELS[role]}</option>)}</select></label></div><div className="mt-4 flex gap-2"><button type="button" className="btn-primary" disabled={saving} onClick={createUser}>{saving ? t.creating : t.createBtn}</button><button type="button" className="btn-secondary" onClick={() => setShowCreate(false)}>{t.cancel}</button></div></div>}
    {error && <div className="rounded-md border border-[var(--color-error)]/30 bg-red-50 p-3 text-sm text-[var(--color-error)]">{error}</div>}
    <div className="overflow-x-auto rounded-[var(--radius-app)] border border-[var(--color-rule)] bg-[var(--color-paper)] shadow-sm"><table className="min-w-full divide-y divide-[var(--color-rule)] text-sm"><thead className="bg-[var(--color-paper-2)] text-left text-xs font-semibold uppercase text-[var(--color-muted)]"><tr><th className="px-4 py-3">{t.user}</th><th className="px-4 py-3">{t.role}</th><th className="px-4 py-3">{t.status}</th><th className="px-4 py-3">{t.perms}</th><th className="px-4 py-3 text-right">{t.actions}</th></tr></thead><tbody className="divide-y divide-[var(--color-rule)]">{users.map((user) => { const role = USER_ROLES.includes(user.role as UserRole) ? (user.role as UserRole) : "VIEWER"; return <tr key={user.id}><td className="px-4 py-3"><div className="font-semibold">{user.displayName || user.username}</div><div className="text-xs text-[var(--color-muted)]">@{user.username}{user.id === currentUserId ? ` · ${t.you}` : ""}</div></td><td className="px-4 py-3"><select className="rounded-md border border-[var(--color-rule)] bg-[var(--color-paper)] px-2 py-1" value={role} disabled={user.id === currentUserId} onChange={(e) => patchUser(user.id, { role: e.target.value })}>{USER_ROLES.map((item) => <option key={item} value={item}>{ROLE_LABELS[item]}</option>)}</select></td><td className="px-4 py-3"><button type="button" disabled={user.id === currentUserId} onClick={() => patchUser(user.id, { isActive: !user.isActive })} className={`rounded-full px-3 py-1 text-xs font-bold ${user.isActive ? "bg-green-100 text-green-700" : "bg-gray-200 text-gray-600"}`}>{user.isActive ? t.active : t.disabled}</button></td><td className="max-w-[360px] px-4 py-3 text-xs text-[var(--color-muted)]">{permissionsForRole(role).map((permission) => permissionLabels[locale][permission]).join(" · ")}</td><td className="px-4 py-3 text-right"><div className="flex justify-end gap-3"><button className="text-[var(--color-accent)] hover:underline" onClick={() => resetPassword(user.id, user.username)}>{t.reset}</button>{user.id !== currentUserId && <button className="text-[var(--color-error)] hover:underline" onClick={() => deleteUser(user.id, user.username)}>{t.del}</button>}</div></td></tr>; })}</tbody></table></div>
    <div className="rounded-[var(--radius-app)] border border-[var(--color-rule)] bg-[var(--color-paper)] p-5"><h2 className="font-bold">{t.matrix}</h2><div className="mt-3 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{roleSummary.map(({ role, permissions }) => <div key={role} className="rounded-md border border-[var(--color-rule)] p-3"><div className="font-semibold">{ROLE_LABELS[role]}</div><div className="mt-1 text-xs text-[var(--color-muted)]">{permissions.map((permission) => permissionLabels[locale][permission]).join(" · ")}</div></div>)}</div></div>
  </div>;
}
